name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Publish with dotnet
      run: |
        chmod +x .github/workflows/scripts/build.sh
        .github/workflows/scripts/build.sh

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: develop # The branch the action should deploy from.
        BRANCH: main # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        SINGLE_COMMIT: true
